version: '3'

services:
  web:
    build:
      context: .
    command: npm run dev
    restart: unless-stopped
    env_file: .env.default
    volumes:
      - .:/usr/src/app
      - ./logs:/logs
    ports:
      - '3000:3000'

  mongo:
    image: mongo:4.2
    restart: always
    env_file: .env.default
    volumes:
      - ./data/:/data/db/
      - ./scripts/mongo-initdb/:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
